### ISSUE TITLE
Add option to use a custom delay

### ISSUE THREAD

**Issue by aahnik** [aahnik/tgcf#122]
I am personally not interested in this feature, but as requested by some people, I thought let me implement it.

@comienzo2093 @tissole 

this custom delay can be introduced by a specifying in the configuration file

```yaml
past:
    delay: 5 # seconds
```

here `5` means seconds. The value passed can be from 0 to 100.

if nothing is passed (don't write this past delay lines), then 0 is used as default.

**Comment by tissole** [comment]
Thanks a lot! I will try this little hack to see how it works. So, a value of 3 means the script will work for 3s and then stops for 3s and so on? Only whole numbers work or I can try something like 2.5, 3.3?

**Comment by ankit-sinha-18** [comment]
Why do you want to get delay for 3.3 sec 😂🤣!!

Btw,only integer value will work ,not the float value.

**Comment by aahnik** [comment]
>  So, a value of 3 means the script will work for 3s and then stops for 3s and so on? Only whole numbers work or I can try something like 2.5, 3.3?

It will forward one message, and then wait for 3s.

And float value is not supported. Why do you need such weird stuff ?

Integer works fine.

**Comment by tissole** [comment]
Before I made a confusion, I wanted to say that the script forwards 3 messages and then waits for 3s, not that it works 3s and waits for 3s. The script currently forwards ~2000msg in ~10 minutes, so 2000msg/600s/=~3.3msg/s. Where do you get the value of one message? I thought that the script will forward ~3msg/s and then waits for 3s if that is the set value. The rate/speed remains the same, only the delay changes, so even if the delay is set to 10 the script will still forward 3msg/s and then stops for 10s.

I think there is confusion between the speed/rate of msg/s of the script and the delay. Maybe you wanted to say that the script works for 1s and then waits for the set value of s From my calculation if the script sents 3msg/s and then waits for 3s, it will forward 2700msg/h - the flood is triggered because the limit is ~2000msg/h.

Value of 4 gives 2160msg/h, somewhere on the edge. That's why I ask for float value. Or maybe my assumptions are wrong.

**Comment by aahnik** [comment]
> The rate/speed remains the same, only the delay changes, so even if the delay is set to 10 the script will still forward 3msg/s and then stops for 10s.


why are you complicating stuff @tissole ? why are are you worrying about insane stuff ?

is this simple thing not clear ?

forward one message -> wait -> forward again -> repeat

we can only set a custom wait time. we cannot change the speed at which one message is forwarded.

and stop worrying about rate limits.

----------

i personally don't use this delay feature. rate limit is inevitable. you cant send more messages than allowed.

-----

end of discussion.

i don't want to waste a single more second on this issue.

**Comment by aahnik** [comment]
hi @tissole, from the next version (wait for the next release) you can set a float value. 

I have already updated the code, but it will be published in the package registry after the next release. (possibly this week)
