### ISSUE TITLE
Buttons are not forwarded

### ISSUE THREAD

**Issue by cat157** [aahnik/tgcf#209]
There is a channel with inline buttons. If you click on the button, a notification appears with information. I would like to forward information from a notification or the information button itself. I attach screenshots with an example of a button.

![first screen](https://user-images.githubusercontent.com/75183660/121497195-dac47780-c9e3-11eb-93c8-5f67d2fd48ae.jpg)
![second screen](https://user-images.githubusercontent.com/75183660/121497211-e021c200-c9e3-11eb-8b95-d834bbed4382.jpg)

**Comment by aahnik** [comment]
So what's the problem ?

tgcf forwards the message with all buttons. If you click on button, you can see notification.

**Comment by cat157** [comment]
tgcf forwards the message without any buttons( testing with the latest update

**Comment by aahnik** [comment]
Hi @cat157, there are two kinds of inline buttons. (means buttons that are attached with messages)

1. Buttons that contain data (when this button is clicked, the bot recieves some data string, and based on that performs some action)
2. Buttons that contain URL (clicking on these buttons is like clicking on  a link)

When you forward a message by hand, the buttons of type 1 are never forwarded. It is not possible to forward them. But buttons of type 2 are forwarded.

Tgcf also forwards buttons of type 2. You must set `show_forwarded_from: true` to enjoy this feature. Otherwise, URL buttons will not get forwarded.

A user account cant create buttons. But if tgcf is being used via a bot account, it can construct buttons. You can write your own plugin to customly deal with buttons.

Docs for creating own plugin https://github.com/aahnik/tgcf/wiki/How-to-write-a-plugin-for-tgcf-%3F (you must know python and telethon for this)

If you want me to develop a custom plugin for you, then contact me https://aahnik.dev
